# nvim-neorocks/nvim-busted-action
#   A composite GitHub action for running busted tests with Neovim
#   https://github.com/nvim-neorocks/nvim-busted-action

name: Run tests

on:
  pull_request: ~
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ["stable"]

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        uses: nvim-neorocks/nvim-busted-action@v1
        with:
          nvim_version: ${{ matrix.neovim_version }}
          before: |
            ls -l /home/runner/work/chatml.nvim/chatml.nvim
            nvim --headless -c "luafile /home/runner/work/chatml.nvim/chatml.nvim/repro/repro.lua" +qall
