# nvim-neorocks/nvim-busted-action
#   A composite GitHub action for running busted tests with Neovim
#   https://github.com/nvim-neorocks/nvim-busted-action

name: Run tests

on:
  pull_request: ~
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ["stable"]

    steps:
      - uses: tree-sitter/setup-action@v2
      - uses: actions/checkout@v3
      - name: Run tests
        uses: nvim-neorocks/nvim-busted-action@v1
        with:
          nvim_version: ${{ matrix.neovim_version }}
          before: |
            cp /home/runner/.luarocks/lib/luarocks/rocks-5.1/tree-sitter-yaml/0.0.30-1/lib/parser/yaml.so $HOME/.luarocks/lib/lua/5.1/parser/yaml.so
